name: 自游股

on:
  workflow_dispatch:
  schedule:
    - cron: 35 3,8 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TxStockAppHeader: ${{ secrets.TXSTOCKAPPHEADER }}
        TxStockAppHeader2: ${{ secrets.TXSTOCKAPPHEADER2 }}
     
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm installnpm 
          npm install cron
          npm install request
      - name: '运行 【txzxtock】'
        if: env.TxStockAppHeader
        run: |
          node txzxtock.js
        env:
          TxStockAppHeader: ${{ secrets.TXSTOCKAPPHEADER }}
          TxStockAppUrl: ${{ secrets.TXSTOCKAPPURL }}
          TxStockWxHeader: ${{ secrets.TXSTOCKWXHEADER }}
  
      - name: '运行 【txzxtock二】'
        if: env.TxStockAppHeader2
        run: |
          node txzxtock.js
        env:
          TxStockAppHeader: ${{ secrets.TXSTOCKAPPHEADER2 }}
          TxStockAppUrl: ${{ secrets.TXSTOCKAPPURL2 }}
          TxStockWxHeader: ${{ secrets.TXSTOCKWXHEADER2 }}
