name: jiuzhangtt

on:
  workflow_dispatch:
  schedule:
    - cron: 15 0,6-23 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        jzttToken: ${{ secrets.JZTTTOKEN }}
        jzttToken2: ${{ secrets.JZTTTOKEN2 }}
   
     
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install 
          npm install cron
          npm install request
      - name: '运行 【jzread】'
        if: env.jzttToken
        run: |
          node jzread.js
        env:
          jzttToken: ${{ secrets.JZTTTOKEN }}
         
  
      - name: '运行 【jzread.js二】'
        if: env.jzttToken2
        run: |
          node jzread.js
        env:
          jzttToken: ${{ secrets.JZTTTOKEN2 }}
   
