name: 自由股2

on:
  workflow_dispatch:
  schedule:
    - cron: 1 3,8 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TxStockCookie: ${{ secrets.TXSTOCKCOOKIE }}
        
     
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install 
          npm install cron
          npm install request
      - name: '运行 【txzxtock】'
        if: env.TxStockCookie
        run: |
          node txzxtockV2.js
        env:
          TxStockCookie: ${{ secrets.TXSTOCKCOOKIE }}
        
      - name: '运行 【txzxtock二】'
        if: env.TxStockCookier2
        run: |
          node txzxtockV2.js
        env:
          TxStockCookie: ${{ secrets.TXSTOCKCOOKIE2 }}
          
